// src/config/managers.js
export const MANAGERS = [
  {
    id: 'rojasroy',
    displayName: 'rojasroy',
    scriptUrl: 'https://script.google.com/macros/s/AKfycbxNNt5An9Xl6e2OtZNCDJmPq2Rn01QzUd09-x6D1581KH3zvNYJxm4Yrs_z_6tvF_L38w/exec',
    das: [
      'alewgut',
      'moralons',
      'aprsanta',
      'brayacax',
      'crolcas',
      'dfaba',
      'daniissm',
      'jesqdav',
      'emmatarg',
      'ferhidal',
      'vyeslany',
      'jretan',
      'josuamo',
      'josuechb',
      'jusmoraa',
      'mquirosm',
      'mjcesp',
      'czmelani',
      'nimariny',
      'samyyy',
      'sofiarv',
      'solanval',
      'uyiriany',
    ],
  },
  {
    id: 'mzfer',
    displayName: 'mzfer',
    scriptUrl: 'https://script.google.com/macros/s/AKfycbwyo6qNY6MgCmORJ3DD7UGQZhXlTvj2ZibbrBHbLWKbRVmF9YJvOY6-XUhLzH2Nst42/exec',
    das: [
      'orteest',
      'calderf',
      'znatali',
      'moaluis',
      'jimalexb',
    ],
  },
  {
    id: 'gimanny',
    displayName: 'gimanny',
    scriptUrl: 'https://script.google.com/macros/s/AKfycbzOpDgsjfUl1wkSg__QWsqY7IJ9HCMvCX3Rp1UtAdLN7u8veu_OPqWrAiIuX-B0nG95/exec',
    das: [
      'Rojaslal',
      'alxacam',
      'anhensen',
      'anthesq',
      'ariefern',
      'brayanc',
      'brayaesq',
      'dgmezza',
      'falldavv',
      'fivargas',
      'gjmc',
      'jeqrodri',
      'glendagl',
      'jalloria',
      'karenjoa',
      'zzmrn',
      'smrnn',
      'fernsofi',
      'sdsegura',
      'nunezvan',
      'bohadaw',
      'natanam',
    ],
  },
];
