// src/config/managers.js
export const MANAGERS = [
  {
    id: 'rojasroy',
    displayName: 'rojasroy',
    spreadsheetId: '1BBANrfMxoQZVUVpSzBo-ilnF5inoasYk_2C159Gf3kU',
    das: [
      'alewgut',
      'moralons',
      'aprsanta',
      'brayacax',
      'crolcas',
      'dfaba',
      'daniissm',
      'jesqdav',
      'emmatarg',
      'ferhidal',
      'vyeslany',
      'jretan',
      'josuamo',
      'josuechb',
      'jusmoraa',
      'mquirosm',
      'mjcesp',
      'czmelani',
      'nimariny',
      'samyyy',
      'sofiarv',
      'solanval',
      'uyiriany',
    ],
  },
  {
    id: 'mzfer',
    displayName: 'mzfer',
    spreadsheetId: '1PXPtjM4jkGfLdsA9vgh7Z-C2SmrO3POixmSMeg-dD4I',
    das: [
      'orteest',
      'calderf',
      'znatali',
      'moaluis',
      'jimalexb',
    ],
  },
  {
    id: 'gimanny',
    displayName: 'gimanny',
    spreadsheetId: '1TODQg7UmxQKo5S0rvwokpOoFVVv7BStlsUdUnsPqD-Q',
    das: [
      'Rojaslal',
      'alxacam',
      'anhensen',
      'anthesq',
      'ariefern',
      'brayanc',
      'brayaesq',
      'dgmezza',
      'falldavv',
      'fivargas',
      'gjmc',
      'jeqrodri',
      'glendagl',
      'jalloria',
      'karenjoa',
      'zzmrn',
      'smrnn',
      'fernsofi',
      'sdsegura',
      'nunezvan',
      'bohadaw',
      'natanam',
    ],
  },
];
